version: '3.7'

services:

  cerzen.migrator:
    image: ${DOCKER_REGISTRY-}cerzenmigrator
    container_name: cerzenmigrator_container
    build:
      context: ../../
      dockerfile: src/CerZen.Migrator/Dockerfile
    environment:
      - ASPNETCORE_Docker_Enabled=true
      - ConnectionStrings__Default=Server=mssqlDb;Database=CerZenDb;User=sa;Password=Super_Encrypted_Passw0rd!
    networks:
      - cerzen
      
networks:
  cerzen:
    external:
      name: cerzen